services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,rds,ec2,elb,efs,iam,sts,logs
      - DEBUG=1
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=ls-nuva4420-JAXA-kIBU-5470-vEgAMEmU264a #(Sempre lembrar de) Adicionar o token gerado na conta do LocalStack
    volumes:
      - "./volume:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge